In [1]:
import pandas as pd

from nlp4bia.datasets.benchmark.distemist import DistemistLoader, DistemistGazetteer
from nlp4bia.datasets.benchmark.symptemist import SymptemistLoader, SymptemistGazetteer
from nlp4bia.datasets.benchmark.medprocner import MedprocnerLoader, MedprocnerGazetteer
from nlp4bia.datasets.benchmark.meddoplace import MeddoplaceLoader, MeddoplaceGazetteer

In [2]:
distemist = DistemistLoader(encoding='utf-8')
symptemist = SymptemistLoader(encoding='latin1')
medprocner = MedprocnerLoader(encoding='utf-8')
meddoplace = MeddoplaceLoader(encoding='utf-8')

distemist_gaz = DistemistGazetteer(encoding='utf-8')
symptemist_gaz = SymptemistGazetteer(encoding='utf-8')
medprocner_gaz = MedprocnerGazetteer(encoding='latin-1')
meddoplace_gaz = MeddoplaceGazetteer(encoding='utf-8')

preprocessing data...
preprocessing data...
preprocessing data...
preprocessing data...
preprocessing data...
preprocessing data...
preprocessing data...
preprocessing data...

In [3]:
distemist.df

,filenameid,mention_class,span,code,sem_rel,is_abbreviation,is_composite,needs_context,extension_esp,text,split
0,es-S0210-56912007000900007-3#164#166,ENFERMEDAD,DM,73211009,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
1,es-S0210-56912007000900007-3#362#376,ENFERMEDAD,deshidratación,34095006,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
2,es-S0210-56912007000900007-3#575#590,ENFERMEDAD,hiperamilasemia,275739007,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
3,es-S0210-56912007000900007-3#715#733,ENFERMEDAD,pancreatitis aguda,197456007,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
4,es-S0210-56912007000900007-3#1402#1459,ENFERMEDAD,formación polipoidea sésil situada junto al es...,88580009,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
...,...,...,...,...,...,...,...,...,...,...,...
7729,es-S0212-16112011000300031-1#845#868,ENFERMEDAD,pinza aorto-mesentérica,235806008,EXACT,None,None,None,None,Mujer de 31 años que ingresa en 2008 en el Ser...,test
7730,es-S0212-16112011000300031-1#1034#1074,ENFERMEDAD,trastorno del comportamiento alimentario,72366004,EXACT,None,None,None,None,Mujer de 31 años que ingresa en 2008 en el Ser...,test
7731,es-S0212-16112011000300031-1#2321#2339,ENFERMEDAD,hipotonía gástrica,46218001,EXACT,None,None,None,None,Mujer de 31 años que ingresa en 2008 en el Ser...,test
7732,es-S0212-16112011000300031-1#528#547,ENFERMEDAD,patología digestiva,119292006,EXACT,None,None,None,None,Mujer de 31 años que ingresa en 2008 en el Ser...,test
7733,es-S0212-16112011000300031-1#346#366,ENFERMEDAD,patología infecciosa,40733004,EXACT,None,None,None,None,Mujer de 31 años que ingresa en 2008 en el Ser...,test

In [4]:
total_data = pd.concat([distemist.df, symptemist.df, medprocner.df, meddoplace.df], ignore_index=True)

In [5]:
total_gaz = pd.concat([distemist_gaz.df, symptemist_gaz.df, medprocner_gaz.df], ignore_index=True)

In [6]:
total_data.shape

(37895, 11)

In [7]:
total_gaz.shape

(546771, 5)

In [8]:
total_data[total_data["split"] == "train"].shape

(25967, 11)

In [13]:
total_data[total_data["split"] == "test"].shape

(11928, 11)

In [14]:
total_data

,filenameid,mention_class,span,code,sem_rel,is_abbreviation,is_composite,needs_context,extension_esp,text,split
0,es-S0210-56912007000900007-3#164#166,ENFERMEDAD,DM,73211009,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
1,es-S0210-56912007000900007-3#362#376,ENFERMEDAD,deshidratación,34095006,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
2,es-S0210-56912007000900007-3#575#590,ENFERMEDAD,hiperamilasemia,275739007,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
3,es-S0210-56912007000900007-3#715#733,ENFERMEDAD,pancreatitis aguda,197456007,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
4,es-S0210-56912007000900007-3#1402#1459,ENFERMEDAD,formación polipoidea sésil situada junto al es...,88580009,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
...,...,...,...,...,...,...,...,...,...,...,...
37890,S0120-41572012000500002-1#2366#2377,FAC_GEN,laboratorio,None,None,None,None,None,None,Se presenta el caso de un recién nacido de sex...,test
37891,S1134-80462009000100005-4#190#198,FAC_GEN,farmacia,None,None,None,None,None,None,"Paciente mujer de 70 años de edad, diagnostica...",test
37892,butlleti_camfic_156#515#524,TRANSPORTE,bicicleta,None,None,None,None,None,None,Paciente de 29 años que acude por omalgia izqu...,test
37893,butlleti_camfic_156#1282#1295,DEPARTAMENTO,traumatología,None,None,None,None,None,None,Paciente de 29 años que acude por omalgia izqu...,test
37894,butlleti_camfic_156#195#198,DEPARTAMENTO,UCI,None,None,None,None,None,None,Paciente de 29 años que acude por omalgia izqu...,test

In [17]:

total_data.groupby("filenameid").size().sort_values(ascending=False)

filenameid
es-S1130-01082008000800009-1#1505#1563    2
es-S0376-78922015000400012-1#326#336      2
es-S0365-66912007001200013-1#542#573      2
es-S1130-05582014000400006-2#191#199      2
es-S1130-05582014000400006-2#158#166      2
                                         ..
es-S0004-06142010000500014-1#334#342      1
es-S0004-06142010000500014-1#359#370      1
es-S0004-06142010000500014-1#397#406      1
es-S0004-06142010000500014-1#416#428      1
es-S0004-06142010000500014-1#2019#2100    1
Length: 37189, dtype: int64

In [18]:
total_data.mention_class.value_counts()

mention_class
SINTOMA          12014
PROCEDIMIENTO     8475
ENFERMEDAD        7734
DEPARTAMENTO      2708
FAC_GEN           2678
GPE_NOM           2046
TRANSPORTE         671
FAC_NOM            438
GPE_GEN            376
GEO_GEN            374
COMUNIDAD          274
IDIOMA              60
GEO_NOM             47
Name: count, dtype: int64