In [1]:
import pandas as pd

from nlp4bia.datasets.benchmark.distemist import DistemistLoader, DistemistGazetteer
from nlp4bia.datasets.benchmark.symptemist import SymptemistLoader, SymptemistGazetteer
from nlp4bia.datasets.benchmark.medprocner import MedprocnerLoader, MedprocnerGazetteer

In [2]:
distemist = DistemistLoader()
symptemist = SymptemistLoader()
medprocner = MedprocnerLoader()

distemist_gaz = DistemistGazetteer()
symptemist_gaz = SymptemistGazetteer()
medprocner_gaz = MedprocnerGazetteer()

preprocessing data...
preprocessing data...
preprocessing data...
preprocessing data...
preprocessing data...
preprocessing data...

In [4]:
distemist.df

,filenameid,mention_class,span,code,sem_rel,is_abbreviation,is_composite,needs_context,extension_esp,text,split
0,es-S0210-56912007000900007-3#164#166,ENFERMEDAD,DM,73211009,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
1,es-S0210-56912007000900007-3#362#376,ENFERMEDAD,deshidratación,34095006,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
2,es-S0210-56912007000900007-3#575#590,ENFERMEDAD,hiperamilasemia,275739007,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
3,es-S0210-56912007000900007-3#715#733,ENFERMEDAD,pancreatitis aguda,197456007,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
4,es-S0210-56912007000900007-3#1402#1459,ENFERMEDAD,formación polipoidea sésil situada junto al es...,88580009,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
...,...,...,...,...,...,...,...,...,...,...,...
7729,es-S0212-16112011000300031-1#845#868,ENFERMEDAD,pinza aorto-mesentérica,235806008,EXACT,None,None,None,None,Mujer de 31 años que ingresa en 2008 en el Ser...,test
7730,es-S0212-16112011000300031-1#1034#1074,ENFERMEDAD,trastorno del comportamiento alimentario,72366004,EXACT,None,None,None,None,Mujer de 31 años que ingresa en 2008 en el Ser...,test
7731,es-S0212-16112011000300031-1#2321#2339,ENFERMEDAD,hipotonía gástrica,46218001,EXACT,None,None,None,None,Mujer de 31 años que ingresa en 2008 en el Ser...,test
7732,es-S0212-16112011000300031-1#528#547,ENFERMEDAD,patología digestiva,119292006,EXACT,None,None,None,None,Mujer de 31 años que ingresa en 2008 en el Ser...,test
7733,es-S0212-16112011000300031-1#346#366,ENFERMEDAD,patología infecciosa,40733004,EXACT,None,None,None,None,Mujer de 31 años que ingresa en 2008 en el Ser...,test

In [3]:
total_data = pd.concat([distemist.df, symptemist.df, medprocner.df], ignore_index=True)

In [4]:
total_gaz = pd.concat([distemist_gaz.df, symptemist_gaz.df, medprocner_gaz.df], ignore_index=True)

In [5]:
total_data.shape

(28223, 11)

In [6]:
total_gaz.shape

(546771, 5)

In [7]:
total_data[total_data["split"] == "train"].shape

(18973, 11)

In [8]:
total_data[total_data["split"] == "test"].shape

(9250, 11)

In [9]:
total_data

,filenameid,mention_class,span,code,sem_rel,is_abbreviation,is_composite,needs_context,extension_esp,text,split
0,es-S0210-56912007000900007-3#164#166,ENFERMEDAD,DM,73211009,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
1,es-S0210-56912007000900007-3#362#376,ENFERMEDAD,deshidratación,34095006,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
2,es-S0210-56912007000900007-3#575#590,ENFERMEDAD,hiperamilasemia,275739007,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
3,es-S0210-56912007000900007-3#715#733,ENFERMEDAD,pancreatitis aguda,197456007,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
4,es-S0210-56912007000900007-3#1402#1459,ENFERMEDAD,formación polipoidea sésil situada junto al es...,88580009,EXACT,None,None,None,None,Mujer de 74 años que ingresó en el hospital po...,train
...,...,...,...,...,...,...,...,...,...,...,...
28218,es-S2340-98942015000100005-1#1732#1795,PROCEDIMIENTO,quimioterapia con trabectedina y adriamicina l...,367336001,NARROW,None,False,False,None,Presentamos el caso de una paciente de 62 años...,test
28219,es-S2340-98942015000100005-1#231#284,PROCEDIMIENTO,quimioterapia adyuvante con carboplatino y pac...,367336001,NARROW,None,False,False,None,Presentamos el caso de una paciente de 62 años...,test
28220,es-S2340-98942015000100005-1#465#468,PROCEDIMIENTO,TAC,77477000,EXACT,None,False,False,None,Presentamos el caso de una paciente de 62 años...,test
28221,es-S2340-98942015000100005-1#533#569,PROCEDIMIENTO,resección anterior de recto superior,172341002,EXACT,None,False,False,None,Presentamos el caso de una paciente de 62 años...,test
28222,es-S2340-98942015000100005-1#574#620,PROCEDIMIENTO,biopsia intraoperatoria de una lesión hepática,274355008,EXACT,None,False,False,None,Presentamos el caso de una paciente de 62 años...,test